# Generated by Django 3.2 on 2023-05-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='info',
            field=models.TextField(default=0, verbose_name='Информация'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес объекта недвижимости')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.products', verbose_name='Выберите продукт для заказа')),
            ],
        ),
    ]
